name: Tests

on:
  workflow_call:
     inputs:
        runs-on:
          required: false
          description: "runs-on self-hosted or ubuntu-latest"
          default: 'ubuntu-latest'
          type: string
######## Variables ########
        MONGODB_URI:
          required: false
          description: "MONGODB_URI"
          type: string          
        MONGODB_DBNAME:
          required: false
          description: "MONGODB_DBNAME"
          type: string
        # ENVIRONMENT:
        #   required: false
        #   description: "ENVIRONMENT"
        #   type: string
        ID_URL:
          required: false
          description: "ID_URL"
          default: 'https://api.alexishr.com/.well-known/jwks.json'
          type: string
        PORT:
          required: false
          description: "PORT"
          type: string
        API_URL:
          required: false
          description: "API_URL"
          default: 'http://localhost:3000'
          type: string 
        FILES_URL:
          required: false
          description: "FILES_URL"
          default: 'http://localhost:3030'
          type: string
########   END Variables  ########
        npm_pre_tests:
          required: false
          description: "npm tests"
          default: 'true'
          type: string   
        npm_tests:
          required: false
          description: "npm tests"
          default: 'true'
          type: string                  
        get_actions_user_id:
          required: false
          description: "Get Actions user id"
          default: 'false'
          type: string
        correct_ownership:
          required: false
          description: "Correct Ownership in GITHUB_WORKSPACE directory"
          default: 'false'
          type: string
        npm_install_with_caching:
          required: false
          description: "npm_install_with_caching"
          default: 'true'
          type: string
        node_version:
          required: false
          description: "node version"
          default: '16'
          type: string
        set_npm:
          required: false
          description: "Set npm 8.5.5"
          default: 'true'
          type: string
        set_npm_global:
          required: false
          description: "Set npm 8.5.5"
          default: 'false'
          type: string
        unset_prepare:
          required: false
          description: "Unset prepare"
          default: 'false'
          type: string 
        publish_code_coverage:
          required: false
          description: "Run tests & publish code coverage"
          default: 'true'
          type: string
        coverage_files:
          required: false
          description: "path to coverage_files"
          default: './coverage/lcov.info'
          type: string 
        coverageLocations:
          required: false
          description: "coverage Locations"
          default: './coverage/lcov.info:lcov'
          type: string
        cache:
          required: false
          description: "actions/cache@v2"
          default: 'false'
          type: string
        dockercompose:
          required: false
          description: "use docker-compose"
          default: 'false'
          type: string
        dockercompose_wth_tests:
          required: false
          description: "use docker-compose with tests"
          default: 'false'
          type: string          
        mongodb:
          required: false
          description: "use mongodb"
          default: 'false'
          type: string        
        upload_code_coverage:
          required: false
          description: "Upload code coverage"
          default: 'false'
          type: string       
        run_test_server:
          required: false
          description: "run_test_server"
          default: 'false'
          type: string             
        run_test_e2e:
          required: false
          description: "run test:e2e"
          default: 'false'
          type: string                  
                     
jobs:
  tests:
    runs-on: ${{ inputs.runs-on }} 
    env:
      COMPOSE_FILE: ./docker-compose.yml
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      MONGODB_URI: ${{ inputs.MONGODB_URI }}
      MONGODB_DBNAME: ${{ inputs.MONGODB_DBNAME }}
      ID_URL: ${{ inputs.ID_URL }}
      API_URL: ${{ inputs.API_URL }}
      FILES_URL: ${{ inputs.FILES_URL }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PORT:  ${{ inputs.PORT }}

    steps: 
      - name: Get Actions user id 
        if: "${{ inputs.get_actions_user_id == 'true' }}"
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id          

      - name: Correct Ownership in GITHUB_WORKSPACE directory
        if: "${{ inputs.correct_ownership  == 'true' }}" 
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}

      - uses: actions/checkout@v2

      - name: Set npm token
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ inputs.node_version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/cache@v2
        if: "${{ inputs.cache  == 'true' }}" 
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-          

      - name: Build Dockerfile
        if: "${{ inputs.dockercompose  == 'true' }}" 
        run: docker-compose up -d app
         
      - name: Set npm 8.5.5
        if: "${{ inputs.set_npm  == 'true' }}"      
        run: npm i -g npm@8.5.5

      - name: Set npm@8.5.5 global
        if: "${{ inputs.set_npm_global  == 'true' }}"      
        run: npm install -location=global npm@8.5.5                

      - name: Unset prepare
        if: "${{ inputs.unset_prepare  == 'true' }}"      
        run: npm pkg delete scripts.prepare

      - name: NPM or Yarn install with caching
        if: "${{ inputs.npm_install_with_caching  == 'true' }}" 
        uses: bahmutov/npm-install@v1.6.0        

      - name: Install
        if: "${{ inputs.npm_pre_tests  == 'true' }}"  
        run: npm ci

      - name: Run lint
        if: "${{ inputs.npm_pre_tests  == 'true' }}"       
        run: npm run lint        

      - name: Build
        if: "${{ inputs.npm_pre_tests  == 'true' }}"       
        run: npm run build

      - name: Start MongoDB
        if: "${{ inputs.mongodb  == 'true' }}"
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.4"

      - name: Wait for Mongo
        if: "${{ inputs.mongodb  == 'true' }}"
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- -t 120 localhost:27017 -- echo "Mongo ready."
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3        

      - name: Check docker
        if: "${{ inputs.dockercompose  == 'true' }}"
        run: docker-compose up -d app

      - name: Run tests
        if: "${{ inputs.npm_tests  == 'true' }}"      
        run: npm run test
#### docker-compose with tests ######

      - name: Build Dockerfile with tests
        if: "${{ inputs.dockercompose_wth_tests  == 'true' }}"
        run: docker-compose up -d app

      - name: Install docker-compose with tests
        if: "${{ inputs.dockercompose_wth_tests  == 'true' }}"
        run: docker-compose run -T app npm ci

      - name: Build docker-compose with tests
        if: "${{ inputs.dockercompose_wth_tests  == 'true' }}"
        run: docker-compose run -T app npm run build

      - name: Run lint docker-compose with tests
        if: "${{ inputs.dockercompose_wth_tests  == 'true' }}"      
        run: docker-compose run -T app npm run lint

      - name: Run tests docker-compose with tests
        if: "${{ inputs.dockercompose_wth_tests  == 'true' }}"
        run: docker-compose run -T app npm test

####  END docker-compose with tests ######        

      - name: Run tests & publish code coverage
        if: "${{ inputs.publish_code_coverage  == 'true' }}"
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:cov
          debug: true
          coverageLocations: |
            ${{github.workspace}}${{ inputs.coverageLocations }}

      - name: Upload code coverage to codecov
        if: "${{ inputs.upload_code_coverage  == 'true' }}"
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          files: ${{ inputs.coverage_files }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Run test starting server
        if: "${{ inputs.run_test_server  == 'true' }}"
        run: npm run test:server

      - name: Run e2e test
        if: "${{ inputs.run_test_e2e  == 'true' }}"
        run: npm run test:e2e          

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          config: .github/config/slack.yaml
        if: failure()
         